### ISSUE TITLE
This code snippet returning an error.

### ISSUE THREAD

**Issue by coding-banana** [adserver-online/php-sdk-examples#5]
https://github.com/adserver-online/php-sdk-examples/blob/568efa8b5deea8be0647f2fb7ca9cb0efeb10f9c/owner/ads_directlink.php#L22

If I try this, with the Id 5, I'm getting an error. 

My code snippet:

```
        $active = $data['active'] === true ? 1 : 0;

        $request = new AdRequest();
        $request->setIdcampaign($data['campaignId']);
        $request->setIsActive($active);
        $request->setName($data['name']);
        $request->setUrl($data['url']);

        $details = new AdDirectLink();

        $request->setDetails($details);

        return $this->adApi->createAd(5, $request);
```

Error:
```
<html><head></head><body><span class="message-body-wrapper">

message | "[404] Client error: `POST https://api.adsrv.net/v2/ad?idformat=5` resulted in a `404 Not Found` response:\n{\"name\":\"Not Found\",\"message\":\"\",\"code\":0,\"status\":404}\n"
-- | --
exception | "Adserver\\ApiException"
file | "/app/app/vendor/adserver-online/php-sdk/src/Api/AdsApi.php"
line | 401
trace | [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
0 | Object { file: "/app/app/vendor/adserver-online/php-sdk/src/Api/AdsApi.php", line: 376, function: "createAdWithHttpInfo", … }

</span></body></html>
```

**Comment by coding-banana** [comment]
Where can I find the Ad ids in the documentation or the code. I couldn't find it anywhere.

**Comment by adserver-online** [comment]
You should check if you pass the correct/existing campaign ID since you can't create an ad without a campaign.

What's the value of $data?

`$request->setIdcampaign($data['campaignId']);`

**Comment by adserver-online** [comment]
> Where can I find the Ad ids in the documentation or the code. I couldn't find it anywhere.

After ad creation, you should get its ID. Also, getCampaign method returns ads with IDs.

**Comment by coding-banana** [comment]
Im Sorry, it was my fault. For debugging purposes Ive had an old campaignId. Thank you for your help
